# Generated by Django 4.1.7 on 2023-04-08 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='num',
        ),
    ]
