# Generated by Django 4.1.7 on 2023-04-01 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 1, 7, 18, 21, 790, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
