# Generated by Django 4.1.7 on 2023-04-08 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_alter_post_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 8, 4, 11, 44, 482386, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
