# Generated by Django 4.1.7 on 2023-05-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_comment_post_comment_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_users',
        ),
    ]
