# Generated by Django 4.1.7 on 2023-04-29 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_alter_post_created_at_like_post_like_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 29, 8, 21, 38, 172086, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
