# Generated by Django 4.1.7 on 2023-05-26 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_remove_post_comment_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
