# Generated by Django 4.1.7 on 2023-04-29 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0001_initial"),
        ("post", "0008_alter_post_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="tag.tag"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 29, 8, 42, 25, 71164, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
