# Generated by Django 4.1.7 on 2023-05-01 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 1, 11, 25, 27, 145567, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
