# Generated by Django 4.1.7 on 2023-05-01 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_rename_comment_comment_content_comment_post_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
    ]
